
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: jira
      POSTGRES_USER: jira
      POSTGRES_PASSWORD: JiraRush
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - jira-network


  jirarush:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DB_URL: jdbc:postgresql://db:5432/jira
      DB_USER: jira
      DB_PASS: JiraRush
      GITHUB_ID: 3d0d8738e65881fff266
      GITHUB_KEY: 0f97031ce6178b7dfb67a6af587f37e222a16120
      GOOGLE_ID: 329113642700-f8if6pu68j2repq3ef6umd5jgiliup60.apps.googleusercontent.com
      GOOGLE_KEY: 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
      GITLAB_ID: b8520a3266089063c0d8261cce36971defa513f5ffd9f9b7a3d16728fc83a494
      GITLAB_KEY: e72c65320cf9d6495984a37b0f9cc03ec46be0bb6f071feaebbfe75168117004
      GITLAB_NAME: GitLab
      EMAIL_HOST: smtp.gmail.com
      EMAIL_USERNAME: jira4jr@gmail.com
      EMAIL_PASS: zdfzsrqvgimldzyj
      EMAIL_PORT: 587
      VIEW_PATH: /app/resources/view/
      MAIL_PATH: /app/resources/mails/
    networks:
      - jira-network
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    depends_on:
      - jirarush
    ports:
      - "80:80"
    networks:
      - jira-network

volumes:
    db_data:
networks:
  jira-network:
    driver: bridge