spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 5
  liquibase:
    enabled: false
  sql:
    init:
      data-locations: classpath:/data4dev/dataForTestProfile.sql
      schema-locations: classpath:/db/schemaTestProf.sql
